# Generated by Django 4.2.14 on 2024-07-27 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0006_address_author_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Address',
            new_name='address',
        ),
    ]
