# Generated by Django 4.2.14 on 2024-07-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0009_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
